# Generated by Django 4.1 on 2022-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_end_time',
            field=models.DateTimeField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_start_time',
            field=models.DateTimeField(blank=True, max_length=10, null=True),
        ),
    ]
