# Generated by Django 4.1 on 2022-09-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_events_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochures',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
    ]
