# Generated by Django 4.1 on 2022-09-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_brochures_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='created_by',
        ),
    ]
