# Generated by Django 4.0 on 2022-09-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_events_num_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='num_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
